version: '2'

services:
  db_nextcloud:
    container_name: db_nextcloud
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    volumes:
      - /var/nextcloud/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud@xiaoxin
      - MYSQL_PASSWORD=nextcloud@xiaoxin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud_net

  app:
    container_name: nextcloud
    image: nextcloud:fpm
    restart: always
    networks:
      - nextcloud_net
    volumes:
      - /data02/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud@xiaoxin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db_nextcloud

  web:
    container_name: nginx_nextcloud
    image: nginx:latest
    ports:
      - 8082:80
      - 8443:443
    networks:
      - nextcloud_net
    restart: always
    volumes:
      - /var/nextcloud/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/nextcloud/nginx/conf.d:/etc/nginx/conf.d
      - /var/nextcloud/nginx/ssl_certs:/etc/nginx/ssl_certs
      - /var/nextcloud/nginx/log:/var/log/nginx
    volumes_from:
      - app

networks:
  nextcloud_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.200.0/24
        gateway: 192.168.200.1